### ISSUE TITLE
Many Problems

### ISSUE THREAD

**Issue by The-Ridder-HS** [bibliocoll/JournalTouch#100]
I have several questions:
1. Is the site still supported on newer PHP versions?
2. Is there still support?
3. Do I need Aleph or can I do it with any other software?

In addition, I have a few problems with the installation. I'm coming to the site, but I can not open the admin menu.

This error appears: (Fatal error: Uncaught Error: Call to undefined function mb_detect_encoding () in C: \ Website \ Website \ sys \ php-gettext \ gettext.inc: 177 Stack trace: # 0 C: \ Website \ Website \ sys \ php-gettext \ gettext.inc (279): _encode ('Help') # 1 C: \ Website \ Website \ sys \ php-gettext \ gettext.inc (286): _gettext ('Help') # 2 C: \ Website \ Website \ admin \ menu.inc (17): __ ('Help') # 3 C: \ Website \ Website \ admin \ index.php (21): include ('C: \\ Website \\ Webs.  ') # 4 {main} thrown in C: \ Website \ Website \ sys \ php-gettext \ gettext.inc on line 177)

I hope you can help me and tell me if it makes sense to use the product.

Yours sincerely

**Comment by tzeumer** [comment]
You might want to try this version, which has some fixes that are not yet merged into this respository: https://github.com/tzeumer/JournalTouch - it (1) should work with any current php version (2) has not really much support and (3) works independently of the library software

**Comment by The-Ridder-HS** [comment]
Fix
