### ISSUE TITLE
Remove list view (?)

### ISSUE THREAD

**Issue by tzeumer** [bibliocoll/JournalTouch#26]
Hmm, I think it is better to use the issue tracker here than the one from my fork. So...

Reasons for this proposal
a) It is broken with frames
b) Lots of data is loaded twice
c) Nearly the same effect could be reached by just removing stuff from the grid view 
d) ... I'm not sure, but I doubt anyone ever would switch to list. With the quick search feature the one and only reason that comes to my mind for using the list is to save bandwith. That leads to c) ...

Or are there really good reasons for that view?

**Comment by krugar** [comment]
i think the cleanest approach is to have one well structured list in the HTML with all available information present and then facilitate the switching of layouts by swapping out css classes. 
stuff that is not displayed in a layout simply gets `display: none`d in the respective css class.

and, related to #17 : 
when disabled in the configuration, should meta-info be in the html but hidden or not be in the html?

**Comment by tzeumer** [comment]
Yes, right. I wanted to do a quick & dirty check for this and use the grid view as base. But at the moment there's only little spare time. But (nearly) halfing the loading size should be worth the afford :)

**Comment by tzeumer** [comment]
Quick & dirty: https://github.com/tzeumer/JournalTouch/tree/pr-replace_listview

The problem is, it is really slow to switch to list view this way (the other way around is fast). But I really wonder, who'd use the list view? If I couldn't get hold of covers I would not really consider using JT in the first place - who'd be attracted by a simple list? :)

**Comment by krugar** [comment]
imho, javascript (or php) should only flip one css class on the view container, the rest should follow from the stylesheet. that way, we can potentially have a list of view layouts and a default configured in `config.php` (akin to the locales).

**Comment by krugar** [comment]
we should fix this in 2 stages: 
1) sort out the html generation, which includes closing #17 
2) get the css to play nicely with the new html structure

work on #23 can commence when 1) is done

**Comment by krugar** [comment]
(a part of this discussion happened in #33)

i'm going to try my hand at this and create a pull request when i'm done. if i manage to come up with something that runs ok on our end, i'd love for you to test it with your data. 

i don't really have a good way of getting other people with installations to weigh in on this topic, but in case theres no css-switchy solution with acceptable performance, i think a config toggle and a deprecation warning seems like a good solution

**Comment by krugar** [comment]
please test this branch with your journal list / setup when you have time.

sorry for the slowness lately, got swamped with other stuff

**Comment by tzeumer** [comment]
There is no hurry. I'm also only doing something if some spare time is left and when I feel like it :)

But hey, this is a very nice improvement. Works very fast, errm... I mean instantaneous, even with about 1000 entries. :)

**Comment by krugar** [comment]
i'll keep this in for 0.1, might make displaying the switch button optional in 0.2
