### ISSUE TITLE
Use language list only for more than two entries

### ISSUE THREAD

**Issue by tzeumer** [bibliocoll/JournalTouch#27]
Currently JT only supports two languages. Most likely it will stay this way for at least some time. I think the (pretty new) list is a good idea if there are more than two languages. For exactly two just a switch seems to be the better option. It's a click less and more obvious.

So I would propose to make the display conditional - if there are more than two languages, show the list, else stick to the old way.

Good idea, bad idea?

**Comment by krugar** [comment]
i wanted the groundwork laid for adding more locales, but i'm fine with the interface reacting to the number of locales configured in a clever fashion. i think it makes sense to separate all 3 cases:
- one locale (dont display anything)
- two locales (display a button/text/flag indicating the not-in-use locale to switch to with one click)
- three or more locales (display either multiple buttons or a dropdown menu)

**Comment by krugar** [comment]
afaik this is done?

**Comment by tzeumer** [comment]
Yep :)
