### ISSUE TITLE
Last cart item always undefined

### ISSUE THREAD

**Issue by tzeumer** [bibliocoll/JournalTouch#28]
The last "my basket" item is always "undefined". On checkout everything is fine...

**Comment by krugar** [comment]
looking into this. it should update if/when the crossref citeproc-json result comes in anyways, but i should be able to set a temporary title and make sure switching to checkout is delayed in case of outstanding ajax requests.

**Comment by krugar** [comment]
abdc1b708067c28b4a6d964f9cea183ce0296a3f fixes one type of this error

**Comment by tzeumer** [comment]
Ah, there. Thanks :)
