### ISSUE TITLE
adopt proper release model

### ISSUE THREAD

**Issue by krugar** [bibliocoll/JournalTouch#29]
get this project back into a deployable state and then switch development away from the master branch so that interested parties can checkout master and not end up with horribly broken code :wink: 

ie: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by tzeumer** [comment]
Thanks for the inspiration :)

Btw. thanks for adding me to the group, but for the same reason I'll stick to pull requests for now. (I really miss a pm option in github...)

**Comment by krugar** [comment]
i'm gonna violate these freshly minted rules horribly by merging feature branch bootstrap_refactoring into branch develop before moving 0.1 to a release branch :goberserk:
mainly because i failed to put the changes into separate commits and cba to do them all again (some of them are quite intertwined anyways).

so: breaking changes between unversioned and 0.1 inbound :-1:
