### ISSUE TITLE
sanitize all url parameters and input fields before using their values

### ISSUE THREAD

**Issue by krugar** [bibliocoll/JournalTouch#32]
never trust the network

**Comment by krugar** [comment]
- create an issn parser function (cf #31 / [comment] (https://github.com/bibliocoll/JournalTouch/commit/b8347f65f9b06ef8e579f7e38efe79312c8a5997#commitcomment-12947944) )
- same for doi (cf http://crosstech.crossref.org/2015/08/doi-regular-expressions.html )
- copy lang/locale parser from MPI internal branch
- do sanity checking of curl output in `sys/ajax_cite.php` and at least attempt to handle obvious error cases gracefully (check what jQuery already does client side and amend)

**Comment by tzeumer** [comment]
Just a quicky regarding the $_REQUEST sanity check. How about some kind of bootstrap that always has to be loaded before a single page. It should include the config file. Then it would be easy to make the valid post/get variables part of the config - and sure, do some sanity or "poisining" checks. I'm not sure if you need an explicit parser for everything - you only have to be sure it can not do something harmful (execute code and stuff). IF someone changes the url manually, just let it fail - as long as it isn't a security risk. The untampred data from us should always be valid...

But bootstrapping would be nice - the only way to do it currently, is in the config file itself. One ugly example is the language setting...

**Comment by krugar** [comment]
this is probably not completely done, but the changes from the bootstrap_refactoring branch move this along quite a bit i hope. closing this for 0.1
