### ISSUE TITLE
Document 0.3->0.4 upgrade path

### ISSUE THREAD

**Issue by krugar** [bibliocoll/JournalTouch#34]
cf 62855c000d4e4ffbbb3f3237413a5dd63b8860a3

bonus level: a script that does the file copy operations

**Comment by tzeumer** [comment]
Haha, thought the same. But bonus complication: you need write rights for nearly everthing :)

**Comment by krugar** [comment]
how did i miss that there already are v0.1 and v0.2 releases here on github :see_no_evil:
