### ISSUE TITLE
ISSN-Images not working

### ISSUE THREAD

**Issue by ekleinod** [bibliocoll/JournalTouch#60]
I'm using the master-branch.

Using the ISSN-images does not work. In the documentation it says to put the ISSN-images in the `img` folder. In the code it says to put the images in the folder specified by `$cfg->sys->data_covers`

Both ways do not work.

`$cfg->sys->data_covers` is empty when used in `sys/class.ListJournals.php` in function `getCover($issn)`. Therefore the images are searched in the root folder of the installation, not in `img`or `data/covers` (as the directory should be when `$cfg->sys->data_covers` is left empty in the config file).

Somehow the initialization of `$cfg->sys->data_covers` in `bootstrap.php` does not work.

Unfortunately I do not have the time for more tests.

**Comment by krugar** [comment]
hey,

thanks for the feedback. that part is going to be obsolete as soon as we bundle up a 0.4 release. @tzeumer has created a very neat admin interface with a web-based cover management suite. you might want to base your testing on the development branch until we have a new release out (there are some directory structure changes between 0.3 and soon-to-be 0.4, so you can save yourself some pain if you do not invest too heavily in 0.3

**Comment by krugar** [comment]
0.4 has been released, closing this.
if upgrading is not an option for some reason and you need pointers to fix this yourself in 0.3, please reopen.
