### ISSUE TITLE
update dependencies documentation

### ISSUE THREAD

**Issue by realsobek** [bibliocoll/JournalTouch#68]
at the website:
https://github.com/bibliocoll/JournalTouch#dependencies

you can read:
PHP 5.3 or newer ([http://www.php.net]), please use the most up-to-date version you have available

Please, remove "5.3 or newer".

My story:
The other day I tried installing JournalTouch 0.3-197-g27ce9e6 on CentOS 7 x86_64.
`firefox http://journaltouch/index.php`
resulted in dark blue bar at the top. about, tags, portfolio buttons were shown on the bar. The website was white, no other function.

`tail -f /var/log/httpd/error_log`
showed this line:
[Sun Apr 03 13:43:39.877648 2016] [:error] [pid 2536] [client 192.168.2.101:50599] PHP Fatal error:  Call to undefined function array_column() in /var/www/html/bibliocoll-JournalTouch-0.3-197-g27ce9e6/index.php on line 108, referer: http://192.168.2.105/admin/

According to documentation:
http://php.net/manual/en/function.array-column.php
the function is 'PHP 5 >= 5.5.0' only.

Stock PHP package on CentOS 7 is version 5.4.16-36.el7_1
Luckily, I could work around with help of RH-SCL repo:
`yum install -y centos-release-scl`

I am going to update to JournalTouch 0.4.1 :)

**Comment by krugar** [comment]
that is a good catch, thank you. i've updated the readme for the `develop` branch.

i'm currently only testing on 5.5.*, 5.6.* and 7.0.* internally, and i would be fine with dropping support for the older versions. any objections there, @tzeumer ?

**Comment by tzeumer** [comment]
I never thought too much (or wrote anything myself) about php versions. So, no objections from me.

**Comment by krugar** [comment]
5.5+ it is, then. might progress to 5.6+ or 7+ as php.net begin sunsetting the older versions.

**Comment by realsobek** [comment]
I found one more mention of PHP 5.3 in the wiki at:
https://github.com/bibliocoll/JournalTouch/wiki/Installation-&-Setup

**Comment by krugar** [comment]
changed that to 5.5+ as well, however the rest of that page needs a complete overhaul as well
