### ISSUE TITLE
' character seems to cause trouble at [View & Print]

### ISSUE THREAD

**Issue by realsobek** [bibliocoll/JournalTouch#82]
- visit http://journaltouch/
- click on 'Acta Psychologica' entry (1st item)
- in pop up window: click on [+] of "Jean-Jacques Temprado : Sensori-motor strategic variations and sequential effects in young and older adults performing a Fitts' task"
- in pop up window: click on [x]
- click on 'my basket' at the top OR click on 'Send articles' at the right hand side
- in pop up window: click on 'Send/Save my articles'; automatic redirection to "http://journaltouch/checkout.php"
- click on [View & Print]
- in the lower half of the window you can see the text:
`"Sensori-motor strategic variations and sequential effects in young and older adults performing a Fitts&"`
it is a link that leads to:
`http://journaltouch/39;%20task`

The link is wrong, from my point of view.

**Comment by krugar** [comment]
0.4.4 hopefully fixed this
