### ISSUE TITLE
Public Service Announcement: Out of Office until 06.06.2016

### ISSUE THREAD

**Issue by krugar** [bibliocoll/JournalTouch#89]
see you folks next month o/
try to not break too much while i'm gone? :)

**Comment by krugar** [comment]
back :)

**Comment by tzeumer** [comment]
Just curious - anything planed in the near future? Especially adding the database code from... whoever wanted to provide it :)

There are stil some nice ideas. E.g. the UB Freiberg had this nice idea: JournalTouch ISSN > ISSN-Reseolver ((http://amsl.technology/tools/issn-resolver/ …) -> ZDB-Link > DDC-Infos > JournalTouch. But there is little point doing this if a database will be added in "a few weeks". 

It feels a bit like dead now. Or worse: like people are adding stuff but only in closed environments.
