### ISSUE TITLE
Problem with journal TOC

### ISSUE THREAD

**Issue by WIASlibrary** [bibliocoll/JournalTouch#98]
One journal returns articles for a completely different journal as well. ISSN is correct in .csv
Journal: "Numerical Linear Algebra with Applications" ISSN 1070-5325, 1099-1506
returns papers from "Noûs" ISSN 0029-4624, 1468-0068 as well.
Both journals appear with corrrect ISSN in journaltocs.

**Comment by tzeumer** [comment]
Hmm, I just checked the "raw data" you get using http://www.journaltocs.ac.uk/api/journals/10705325?output=articles&user=>YOUR-JOURNALTOC-MAIL

While the ISSN search on the JournalTocs website yields the correct result, the API does return Noûs articles, too. These articles have the wrong ISSN recorded in <dc:source>. I would suggest that you tell JournalTocs about the (imho) obvious error. There are lots of contacting options (in the footer of the http://www.journaltocs.ac.uk/) and in my experience, they are very quick responders.

**Comment by WIASlibrary** [comment]
Thank you, the error has been fixed quickly by JournalTocs.

**Comment by tzeumer** [comment]
Great :)
